name: 🐛 Bug report
description: "Create a report to help us improve Open MatSciML Toolkit"
labels: bug
title: "[Bug]: "

body:
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: Paste the stack trace, screen clips of the problem, etc.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the problem
      description: Enumerate and/or describe the steps to reproduce this problem.
    validations:
      required: true
  - type: textarea
    id: specifications
    attributes:
      label: Specifications
      description: What version of the package are you using, and on what kind of hardware/software environment? Please consider including the output of `pip freeze` here.
    validations:
      required: true
